[book]
title = "Rust Projektvorschläge für Einsteiger"
authors = ["Thorsten"]
language = "de"
src = "src"

[output.html]
default-theme = "navy"
preferred-dark-theme = "navy"
additional-js = ["mermaid.min.js", "mermaid-init.js"]


